[project]
name = "python-libs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jupyterlab>=4.3.0",
    "ruff>=0.7.2",
]
